title: <p align="center"> Nora Kirkizh </p>

logo: "/images/YDq3u6jA.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_Kirkizh.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nora-kirkizh-b13414170/">LinkedIn</a> |
  <a href="https://github.com/norakirkizh">GitHub</a>
  </p>
  
  <p align="justify">
  I am a PhD student in Computational Social Science at Technical University of Munich in Germany.
  <br><br>
  I am currently a Researcher at GESIS – Leibniz Institute for Social Sciences.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
