title: <p align="center"> Nora Kirkizh </p>

logo: "/images/IMG_4539.JPG?raw=true"

description:
  <p align="center">
  <a href="CV_Kirkizh.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nora-kirkizh-b13414170/">LinkedIn</a> |
  <a href="https://github.com/norakirkizh">GitHub</a>
  </p>
  
  <p align="justify">
  I am a computational social scientist, finishing PhD in Political Science at Technical University of Munich (TUM) in Germany. I am doing research within the Chair of Computational Social Science and Big Data at TUM led by Prof. Jürgen Pfeffer. My research focus is quantitative methods, causal inference, media and political behavior.
  <br><br>
  I was also a Research Associate at GESIS – Leibniz Institute for the Social Sciences, Department of Computational Social Science.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
